---
title: Потужні візерунки
hero_image: images/banner.png
description:
  - Create a piece of inspirational art that can be scaled using repeated
  - patterns
meta_title: Python coding projects for kids and teens | Powerful patterns
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a piece of inspirational art with Python using repeated patterns.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ти зробиш
  - 
    title: Свою ідею
    completion:
      - engaged
  - 
    title: Будуй та тестуй - Мотив
    completion:
      - engaged
  - 
    title: Розширюй та тестуй - Візерунок
    completion:
      - internal
  - 
    title: Контрольний список
    challenge: true
  - 
    title: Вдосконалення твого проєкту
