---
title: Барвисті візерунки
hero_image: images/banner.png
description: Зроби витвір мистецтва, який можна масштабувати з використанням повторюваних візерунків
meta_title: Проєкти з кодування для дітей і підлітків | Барвисті візерунки
meta_description: Вивчай Python з проєктами кодування Raspberry Pi Foundation для дітей і підлітків. Створи твір мистецтва за допомогою Python, використовуючи повторювані візерунки.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Що ти зробиш
  - title: Початок роботи
    completion:
      - engaged
  - title: Створи мотив
    completion:
      - internal
  - title: Зроби візерунок
    completion:
      - external
  - title: Додаткове завдання
    challenge: true
  - title: Що ти тепер вмієш?
