---
title: Krachtige patronen
hero_image: images/banner.png
description:
  - Maak een stukje inspirerende kunst dat kan worden geschaald met behulp van herhaalde
  - patronen
meta_title: Python-coderingsprojecten voor kinderen en tieners | Krachtige patronen
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Creëer een inspirerend kunstwerk met Python met behulp van herhaalde patronen.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Aan de slag
    completion:
      - engaged
  - 
    title: Maak een motief
    completion:
      - internal
  - 
    title: Maak het patroon
    completion:
      - external
  - 
    title: Uitdaging
    challenge: true
  - 
    title: Wat kun je verder nog doen?
