---
title: Krachtige patronen
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Jouw idee
  - 
    title: Bouwen en testen - Patroon
    completion:
      - engaged
  - 
    title: Uitbreiden en testen - Patroon
    completion:
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Delen
  - 
    title: Wat kun je verder nog doen?
