title: Powerful patterns
hero_image: images/banner.png
description: Create a piece of inspirational art that can be scaled using repeated patterns
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test - Motif
  - title: Expand and test - Pattern
  - title: Share
  - title: Upgrade your project
  - title: Reflect
  - title: What next?
