---
title: Patrymau pwerus
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Dy syniad
  - 
    title: Adeiladu a phrofi - Motiff
    completion:
      - engaged
  - 
    title: Ehangu a phrofi - Patrwm
    completion:
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Uwchraddio eich prosiect
  - 
    title: Rhannu
  - 
    title: Profwch eich hun
