---
title: Super padrões
hero_image: images/banner.png
description: Crie uma inspiradora obra de arte, que pode ser desenhada com padrões escaláveis
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: A sua ideia
  - 
    title: Construir e testar — Motivo
    completion:
      - engaged
  - 
    title: Expandir e testar — Padrão
    completion:
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: Compartilhar
  - 
    title: E agora?
