---
title: Super padrões
hero_image: images/banner.png
description:
  - Crie uma inspiradora obra de arte que possa ser dimensionada usando-a repetidamente
  - padrões
meta_title: Projetos de codificação Python para crianças e adolescentes | Super padrões
meta_description: Aprenda Python com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Crie uma obra de arte inspiradora com Python usando padrões repetidos.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: O que você irá fazer
  - title: A sua ideia
  - title: Construir e testar — Motivo
    completion:
      - engaged
  - title: Expandir e testar — Padrão
    completion:
      - internal
  - title: Lista de tarefas
    completion:
      - external
  - title: Melhore o seu projeto
  - title: Compartilhar
  - title: E agora?
