---
title: Powerful patterns
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: ನಿಮ್ಮ ಕಲ್ಪನೆ
  - 
    title: Build and test - Motif
    completion:
      - engaged
  - 
    title: Expand and test - Pattern
    completion:
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: ಮುಂದೆ ಏನು?
