---
title: Powerful patterns
hero_image: images/banner.png
description:
  - Create a piece of inspirational art that can be scaled using repeated
  - patterns
meta_title: Python coding projects for kids and teens | Powerful patterns
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a piece of inspirational art with Python using repeated patterns.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: ಪರಿಚಯ
  - 
    title: ಪ್ರಾರಂಭಿಸಿ
    completion:
      - engaged
  - 
    title: Create a motif
    completion:
      - internal
  - 
    title: Make the pattern
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
