---
title: Patrones poderosos
hero_image: images/banner.png
description:
  - Create a piece of inspirational art that can be scaled using repeated
  - patterns
meta_title: Python coding projects for kids and teens | Powerful patterns
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a piece of inspirational art with Python using repeated patterns.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Introducción
  - 
    title: Tu idea
  - 
    title: Construye y prueba - Motivo
    completion:
      - engaged
  - 
    title: Expande y prueba - Patrón
    completion:
      - internal
  - 
    title: Reflexión
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
