---
title: Potężne wzory
hero_image: images/banner.png
description:
  - Stwórz inspirującą sztukę, którą można skalować za pomocą powtarzania
  - wzory
meta_title: Projekty programistyczne w Pythonie dla dzieci i młodzieży | potężne wzory
meta_description: Naucz się języka Python z projektami programistycznymi Fundacji Raspberry Pi dla dzieci i młodzieży. Stwórz inspirującą sztukę za pomocą Pythona używając powtarzających się wzorów.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Zrobisz to
  - 
    title: Zaczynamy
    completion:
      - engaged
  - 
    title: Create a motif
    completion:
      - internal
  - 
    title: Make the pattern
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
