---
title: Motifs puissants
hero_image: images/banner.png
description:
  Crée une œuvre d'art inspirante qui peut être mise à l'échelle en utilisant
  des motifs répétés
meta_title: Projets de codage Python pour enfants et adolescents | Motifs puissants
meta_description: Apprends Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Crée une œuvre d'art inspirante avec Python en utilisant des motifs répétés.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Ce que tu vas faire
  - title: Commencer
    completion:
      - engaged
  - title: Créer un motif
    completion:
      - internal
  - title: Faire le motif
    completion:
      - external
  - title: Défi
    challenge: true
  - title: Que peux-tu faire maintenant ?
