---
title: Motifs puissants
hero_image: images/banner.png
description: Créer une œuvre d'art inspirante qui peut être mise à l'échelle en utilisant des motifs répétés
version: 4
listed: true
copyedit: true
last_tested: '2021-10-06'
steps:
  - 
    title: Introduction
  - 
    title: Ton idée
  - 
    title: Construire et tester - Motif
    completion:
      - engaged
  - 
    title: Développer et tester - Motif
    completion:
      - internal
  - 
    title: Réflexion
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
