---
title: Motifs puissants
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Ton idée
  - 
    title: Construire et tester - Motif
    completion:
      - engaged
  - 
    title: Développer et tester - Motif
    completion:
      - internal
  - 
    title: Liste de contrôle
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
